branches:
  only:
  - version
env:
  global:
  - ENCRYPTION_LABEL: "<.... encryption label from previous step ....>"
  - COMMIT_AUTHOR_EMAIL: "cedric.burceaux@gmail.com"
after_success:
  - deploy-prod-travis.sh